pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        flatDir {
            dirs 'app/libs' // This is where your .aar files are
        }
        maven { url "https://jitpack.io" }
        maven { url 'https://plugins.gradle.org/m2/' }
    }
}
rootProject.name = "RecyclerView"
include ':app'
